cnizzardini/cakephp-swagger-bake

- src/Lib/Annotation/AbstractParameter.php
- src/Lib/Annotation/SwagForm.php
- src/Lib/Annotation/SwagHeader.php
- src/Lib/Annotation/SwagQuery.php
- src/Lib/OpenApi/Schema.php
- src/Lib/OpenApi/SchemaProperty.php
- src/Lib/Operation/OperationHeader.php
- src/Lib/Operation/OperationQueryParameter.php
- src/Lib/Operation/OperationRequestBody.php
- Moved SwagForm, SwagHeader, and SwagQuery logic into an abstract
class: AbstractParameter since all the code is the same.
- Added enum to Schema and SchemaProperty
- Updated Operation classes to support the new enum property
> #39 Added support for Schema:enum

- README.md
- src/Lib/Annotation/AbstractParameter.php
- src/Lib/Annotation/SwagForm.php
- src/Lib/Annotation/SwagHeader.php
- src/Lib/Annotation/SwagQuery.php
- src/Lib/Factory/ParameterFromAnnotationFactory.php
- src/Lib/OpenApi/Parameter.php
- src/Lib/OpenApi/Schema.php
- src/Lib/OpenApi/SchemaProperty.php
- src/Lib/Operation/OperationHeader.php
- src/Lib/Operation/OperationQueryParameter.php
- src/Lib/Operation/OperationRequestBody.php
- tests/TestCase/Lib/Operation/OperationHeaderTest.php
- tests/TestCase/Lib/Operation/OperationQueryParameterTest.php
#60 PR
- Updated README
- Updated Annotations for SwagForm, SwagHeader, SwagQuery and
AbstractParameter
- Created a Parameter Factory
- Added additional fields to OpenApi classes
- Added support in Operation classes.
- Added unit tests
> #60 Additional support for OpenAPI Parameter Object specification

- src/Lib/OpenApi/SchemaProperty.php
- src/Lib/Schema/SchemaPropertyValidation.php
- tests/TestCase/Lib/Schema/SchemaPropertyValidationTest.php
Refactored SchemaPropertyValidation a bit and added assignMinLength()
to accomplish main task. Added unit test.
> #74 notEmpty validations

- README.md
- src/Lib/Annotation/AbstractParameter.php
- src/Lib/Annotation/SwagDtoProperty.php
- src/Lib/AnnotationLoader.php
- src/Lib/Operation/DtoParser.php
- src/Lib/Operation/OperationQueryParameter.php
- src/Lib/Operation/OperationRequestBody.php
- tests/TestCase/Lib/Annotations/SwagDtoTest.php
- tests/TestCase/Lib/Operation/OperationQueryParameterTest.php
- tests/test_app/src/Dto/EmployeeData.php
- Moved DTO logic into DtoParser for Query and Body operations
- Added `@SwagDtoProperty`
- Fixed type for AbstractParameter::example (is mixed not array)
- Updated README
- Added and updated unit tests
> #61 Add additional functionality to SwagDto

- README.md
- src/Lib/Annotation/AbstractSchemaProperty.php
- src/Lib/Annotation/SwagDtoForm.php
- src/Lib/Annotation/SwagDtoQuery.php
- src/Lib/Annotation/SwagEntityAttribute.php
- src/Lib/AnnotationLoader.php
- src/Lib/Operation/DtoParser.php
- src/Lib/Operation/OperationRequestBody.php
- src/Lib/Schema/SchemaPropertyFromAnnotationFactory.php
- tests/test_app/src/Dto/EmployeeData.php
- Split SwagDtoProperty into new annotations: SwagDtoQuery & SwagDtoForm
- Extend SwagDtoForm, SwagForm, and SwagEntityAttribute from
AbstractSchemaProperty
- Refactored DtoParser to support changes
- Extend SwagDto from AbstractParameter
- Updated README
- Updated unit tests
> #70 Refactored SwagDtoProperty and SwagForm

- .travis.yml
- composer.json
- phpmd.xml
- src/Controller/Component/SwaggerUiComponent.php
- src/Lib/Configuration.php
- src/Lib/Extension/CakeSearch/Extension.php
- Add phpmd to composer, travis, and a ruleset file.
- Deprecated getHotReload in favor of isHotReload in Configuration.php
- Change SwaggerUIComponent to use isHotReload
- SuppressWarning in Extension.php
> Implemented PHPMD and a few issues it found

- .gitignore
- src/Command/BakeCommand.php
- src/Command/InstallCommand.php
- src/Command/ModelCommand.php
- src/Command/RouteCommand.php
- src/Lib/Configuration.php
- src/Lib/Swagger.php
- tests/TestCase/Command/BakeCommandTest.php
- tests/TestCase/Command/InstallCommandTest.php
- tests/TestCase/Command/ModelCommandTest.php
- tests/TestCase/Command/RouteCommandTest.php
- tests/bootstrap.php
Improve code coverage for console commands
> Code coverage

- .travis.yml
following cakephp's lead here.
> Use ubuntu bionic in travis ci

- src/Command/BakeCommand.php
- src/Command/CommandTrait.php
- src/Command/ModelCommand.php
- src/Command/RouteCommand.php
- src/Lib/Factory/SwaggerFactory.php
- src/Lib/Operation/OperationSecurity.php
Adds changes from v1.4.2 to develop branch
> Master to develop

- src/Lib/Operation/OperationFromRouteFactory.php
- src/Lib/Operation/OperationPath.php
- src/Lib/Swagger.php
- tests/TestCase/Lib/Annotations/SwagPathParameterTest.php
- tests/TestCase/Lib/Operation/OperationPathTest.php
> Use schema to set path parameter `type`, `description`, and `format`

- README.md
Maybe you want to change the method to match `toString`.
> typo in docs

- assets/x-swagger-bake.yaml
- src/Lib/MediaType/Generic.php
- src/Lib/MediaType/HalJson.php
- src/Lib/MediaType/Xml.php
- src/Lib/OpenApi/Schema.php
- src/Lib/Operation/OperationRequestBody.php
- src/Lib/Operation/OperationResponse.php
- tests/TestCase/Lib/MediaType/HalJsonTest.php
- Adds HAL+JSON, XML, and Generic media types
- Refactor OperationResponse to use formatters
- Adds unit test for HAL+JSON formatter
> Adds HAL+JSON and other media type formatters #159

- src/Lib/Annotation/AbstractSchemaProperty.php
- src/Lib/Annotation/SwagEntityAttribute.php
- src/Lib/OpenApi/SchemaProperty.php
- src/Lib/Schema/SchemaPropertyFromAnnotationFactory.php
- tests/TestCase/Lib/Annotations/SwagEntityAttributeTest.php
- tests/test_app/src/Model/Entity/Employee.php
Changes SchemaProperty::example to `@var mixed`
> Add SwagEntityAttribute::example

- src/Lib/OpenApi/SchemaProperty.php
- src/Lib/Schema/SchemaFactory.php
- src/Lib/Swagger.php
> 1.next cs fix

- composer.json
- src/Lib/Annotation/SwagDtoRequestBody.php
- src/Lib/AnnotationLoader.php
- src/Lib/Operation/DtoParser.php
- src/Lib/Operation/OperationRequestBody.php
- tests/test_app/src/Dto/EmployeeData.php
Support DTOs for XML and JSON request types #204
- Adds support for XML/JSON DTO via SwagDtoRequestBody annotation
- Deprecates SwagDtoForm in favor of SwagDtoRequestBody
> Support DTOs for XML and JSON request types

- composer.json
- src/Lib/Annotation/SwagDtoForm.php
- src/Lib/Annotation/SwagDtoRequestBody.php
- src/Lib/Operation/OperationRequestBody.php
- Removes minimum-stability and prefer-stable
- Sets CakePHP version constraint to `~4.0`
- Sets MixerApi/Core to `~1.0`
> Updates composer and fixes CS issues

- docs/annotations.md
> SwagDtoRequestBody documentation

- .github/workflows/php.yml
- src/Lib/OpenApi/Schema.php
Change Schema::properties to accept both Schema and SchemaProperty
> Modify schema properties

- src/Lib/Model/ModelScanner.php
> Allow ModelDecorators to be created without routeDecorator

- .github/workflows/php.yml
- composer.json
- docs/annotations.md
- phpmd.xml
- src/Lib/Annotation/SwagEntity.php
- src/Lib/Model/ModelScanner.php
- src/Lib/OpenApi/Schema.php
- src/Lib/Schema/SchemaFactory.php
- src/Lib/Swagger.php
- tests/TestCase/Command/ModelCommandTest.php
- tests/TestCase/Lib/Annotations/SwagEntityTest.php
Resolves #224 and sets build to only run php 7.3 and 7.4 (removing 7.2)
> Feature/224 - Add support for hidden entities

- docs/annotations.md
- src/Lib/Annotation/SwagEntity.php
- src/Lib/Model/ModelScanner.php
- src/Lib/OpenApi/Schema.php
- src/Lib/Schema/SchemaFactory.php
- src/Lib/Swagger.php
- tests/TestCase/Lib/Annotations/SwagEntityTest.php
- tests/test_app/src/Model/Entity/DepartmentEmployee.php
- tests/test_app/src/Model/Entity/EmployeeTitle.php
Maintains prior isVisible functionality. Accomplishes features by introducing new isPublic attribute.
Resolves #224
> Reverses breaking change by introducing no SwagEntity attribute

- docs/annotations.md
Resolves #232
Improves documentation for SwagPaginator and SwagSearch.
> SwagPaginator and SwagSearch documentation improvements.

- docs/extensions.md
> Fixes broken links #239

- src/Lib/OpenApi/Schema.php
> Remove isPublic from OpenAPI output

- src/Lib/Annotation/SwagResponseSchema.php
> mimeTypes is an array, not string.

- README.md
- src/Lib/Operation/ExceptionHandler.php
- tests/TestCase/Lib/Operation/ExceptionHandlerTest.php
- tests/TestCase/Lib/SwaggerOperationTest.php
- tests/test_app/src/Controller/EmployeesController.php
> Require using FQN for exception `@throws` to resolve bug

- .github/workflows/php.yml
- .gitignore
- composer.json
Use ubuntu 20 in github action jobs and fix php coveralls reporting.
> Use ubuntu 20 for github actions and fix coveralls

- src/Lib/Schema/SchemaPropertyFromAnnotationFactory.php
> Add Format field to SchemaProperty from SwagEntityAttribute

- src/Lib/Operation/ExceptionHandler.php
> Fixed Undefined index ExceptionHandler.php, line 91

- phpmd.xml
- src/Lib/Annotation/AbstractSchemaProperty.php
- src/Lib/OpenApi/Schema.php
- src/Lib/OpenApi/SchemaInterface.php
- src/Lib/OpenApi/SchemaProperty.php
- src/Lib/OpenApi/SchemaTrait.php
- src/Lib/Swagger.php
- Enables additional phpmd rules and makes existing stricter
- Light refactor to Schema and SchemaProperty to reduce SA scores
> Code cleanup based on phpmd static analysis

- src/Lib/Configuration.php
- src/Lib/Model/ModelScanner.php
- src/Lib/OpenApi/SchemaProperty.php
- src/Lib/Route/RouteScanner.php
- src/Lib/Schema/SchemaFromYamlFactory.php
- src/Lib/Schema/SchemaPropertyFromYamlFactory.php
- tests/test_app/config/swagger_bake.php
Builds off of #273 and resolves pre-existing issues in Configuration and ModelScanner
- Ensure namespace arrays are unique in Configuration
- Uses table namespace from swagger_bake config in ModelScanner
> Nested objects with config fixes

- src/Command/CommandTrait.php
> Duplicate configs running swagger bake command with multiple plugins 

- src/Lib/MediaType/AbstractMediaType.php
- src/Lib/MediaType/Generic.php
- src/Lib/MediaType/HalJson.php
- src/Lib/MediaType/JsonLd.php
- src/Lib/MediaType/Xml.php
- src/Lib/Operation/OperationResponse.php
- src/Lib/Route/RouteScanner.php
> XML, JSON-LD, and HAL+JSON schema examples for non-CRUD endpoints

- .github/workflows/php.yml
- README.md
- composer.json
- grumphp.yml
- src/Lib/MediaType/AbstractMediaType.php
- src/Lib/MediaType/Generic.php
- src/Lib/MediaType/HalJson.php
- src/Lib/MediaType/JsonLd.php
- src/Lib/Operation/OperationResponse.php
- src/Lib/Operation/OperationResponseAssociation.php
- src/Lib/Schema/SchemaFactory.php
- src/Lib/Swagger.php
Cleans up static analyzers, adds grumphp, and removes old versions of PHP from github actions.
> 2 next cleanup

- README.md
- assets/swagger_bake.php
- docs/attributes.md
- src/Lib/Attribute/OpenApiOperation.php
- src/Lib/Configuration.php
- src/Lib/Operation/OperationFromRouteFactory.php
- src/Lib/Swagger.php
- tests/TestCase/Lib/SwaggerTest.php
- tests/test_app/src/Controller/EmployeesController.php
> Drop support for isPut in OpenApiOperation and improve readme

- .github/workflows/php.yml
- README.md
- assets/swagger_bake.php
- composer.json
- docs/attributes.md
- docs/events.md
- docs/extensions.md
- src/Lib/Attribute/AbstractSchemaProperty.php
- src/Lib/Attribute/OpenApiHeader.php
- src/Lib/Attribute/OpenApiPath.php
- src/Lib/Attribute/OpenApiQueryParam.php
- src/Lib/OpenApi/Schema.php
- src/Lib/OpenApi/SchemaProperty.php
> Documentation for 2.x

- docs/attributes.md
- src/Lib/Attribute/OpenApiOperation.php
- src/Lib/OpenApi/Operation.php
- src/Lib/OpenApi/Path.php
- src/Lib/OpenApi/SchemaProperty.php
- src/Lib/OpenApiPathGenerator.php
- src/Lib/OpenApiSchemaGenerator.php
- src/Lib/Operation/OperationFromRouteFactory.php
- src/Lib/Swagger.php
- See #338
- Documentation cleanup
- Refactor Swagger class splitting out schema and path generation
>  Change default sort of operations and other refactors

- README.md
- docs/events.md
- src/Lib/OpenApiPathGenerator.php
> path event

- README.md
- composer.json
> Release prep

- src/Lib/OpenApi/SchemaProperty.php
- tests/TestCase/Lib/OpenApi/SchemaPropertyTest.php
- tests/TestCase/Lib/OpenApi/SchemaTest.php
> Fixes 346: Examples are defaulting to a string of "null"

- .github/workflows/php.yml
> Adds php 8.1 to matrix

- .github/workflows/php.yml
> fix test matrix

- README.md
- src/Lib/OpenApi/Content.php
- src/Lib/OpenApi/Operation.php
- src/Lib/OpenApi/OperationExternalDoc.php
- src/Lib/OpenApi/Parameter.php
- src/Lib/OpenApi/Path.php
- src/Lib/OpenApi/RequestBody.php
- src/Lib/OpenApi/Response.php
- src/Lib/OpenApi/Schema.php
- src/Lib/OpenApi/SchemaProperty.php
- src/Lib/OpenApi/Xml.php
>  PHP 8.1 JsonSerializable::jsonSerialize() Deprecated warnings

- README.md
- src/Lib/Operation/OperationDocBlock.php
- tests/TestCase/Lib/Operation/OperationDocBlockTest.php
> Support `@link` tag for external documentation

- src/Lib/Operation/OperationResponseAssociation.php
- tests/TestCase/Lib/Operation/OperationResponseTest.php
>  OpenApiResponse association permenantly modifies the Schema

- .github/workflows/php.yml
- src/Lib/OpenApi/Content.php
- src/Lib/OpenApi/Operation.php
- src/Lib/OpenApi/Schema.php
- src/Lib/OpenApiSchemaGenerator.php
- src/Lib/Operation/OperationRequestBody.php
- src/Lib/Operation/OperationResponse.php
- tests/TestCase/Lib/MediaType/GenericTest.php
- tests/TestCase/Lib/MediaType/HalJsonIntegrationTest.php
- tests/TestCase/Lib/MediaType/HalJsonTest.php
- tests/TestCase/Lib/MediaType/JsonLdIntegrationTest.php
- tests/TestCase/Lib/MediaType/JsonLdTest.php
- tests/TestCase/Lib/Operation/OperationRequestBodyYamlTest.php
- tests/TestCase/Lib/Operation/OperationResponseAssociationTest.php
- tests/TestCase/Lib/Operation/OperationResponseTest.php
- tests/TestCase/Lib/SwaggerOperationTest.php
> Remove custom read/write schemas

- docs/attributes.md
- src/Lib/Attribute/OpenApiResponse.php
- src/Lib/OpenApi/Content.php
- src/Lib/OpenApi/JsonSchemaTrait.php
- src/Lib/OpenApi/Response.php
- src/Lib/OpenApi/Schema.php
- src/Lib/OpenApi/SchemaInterface.php
- src/Lib/OpenApi/SchemaProperty.php
- src/Lib/OpenApi/SchemaTrait.php
- src/Lib/OpenApi/Xml.php
- src/Lib/Operation/OperationResponseAssociation.php
- src/Lib/Utility/ArrayUtility.php
- tests/TestCase/Lib/MediaType/HalJsonTest.php
- tests/TestCase/Lib/MediaType/JsonLdTest.php
- tests/TestCase/Lib/OpenApi/ContentTest.php
- tests/TestCase/Lib/OpenApi/ResponseTest.php
- tests/TestCase/Lib/Operation/OperationResponseAssociationTest.php
> Associated schema depth

- composer.json
Allow mixerapi/core ^0.2 || ^1.0
> mixerapi api v1 compat

- src/Lib/Operation/OperationResponse.php
- tests/TestCase/Lib/Operation/OperationResponseTest.php
> Resolves OpenApiResponse::schema array bug

- docs/attributes.md
- src/Lib/Attribute/OpenApiSchema.php
- src/Lib/OpenApi/Schema.php
- src/Lib/Operation/OperationRequestBody.php
- src/Lib/Operation/OperationResponse.php
- src/Lib/Swagger.php
- tests/TestCase/Lib/Attribute/OpenApiDtoTest.php
- tests/TestCase/Lib/Attribute/OpenApiResponseTest.php
- tests/TestCase/Lib/Attribute/OpenApiSchemaTest.php
- tests/TestCase/Lib/Operation/OperationRequestBodyTest.php
- tests/TestCase/Lib/Operation/OperationResponseTest.php
- tests/test_app/src/Controller/EmployeesController.php
- tests/test_app/src/Dto/CustomResponseSchemaPublic.php
- tests/test_app/src/Dto/EmployeeDataRequestPublicSchema.php
> Support adding DTOs and Responses to openapi components schemas

- assets/x-swagger-bake.yaml
> OpenApiPaginator attribute generates duplicated "direction" parameter

- src/Lib/OpenApi/Path.php
- src/Lib/OpenApi/SchemaProperty.php
- src/Lib/OpenApi/SchemaTrait.php
- src/Lib/Schema/SchemaPropertyFromYamlFactory.php
- tests/test_app/config/swagger-with-existing.yml
> Allow empty type from openapi yaml

- .github/workflows/php.yml
- composer.json
- src/Controller/SwaggerController.php
Also suppresses a camel case property warning being emitted by phpmd.
> Adds php 8.1, cakephp ~4.3.0 + ^4.4.0 to Github Action CI

- src/Lib/Model/ModelScanner.php
- src/Lib/Route/RouteDecorator.php
- tests/TestCase/Lib/Route/RouteDecoratorTest.php
This ports a 1.x bug fix into 2.x, see #430
> Support controllers defined in snake_case form from routes

- src/Lib/Utility/DataTypeConversion.php
- tests/TestCase/Lib/Utility/DataTypeConversionTest.php
> Map timestamp to OA type of string and OA format of date-time

- src/Lib/MediaType/Generic.php
- src/Lib/MediaType/HalJson.php
- src/Lib/MediaType/JsonLd.php
- src/Lib/MediaType/MediaTypeTrait.php
- tests/TestCase/Lib/MediaType/GenericTest.php
- tests/test_app/config/swagger-with-generic-collection.yml
> Fixes issues with OpenApiResponse associations when schemaType is array

- docs/attributes.md
- src/Lib/Extension/CakeSearch/Attribute/OpenApiSearch.php
- src/Lib/Extension/CakeSearch/Extension.php
- tests/TestCase/Lib/Extension/CakeSearch/ExtensionTest.php
- tests/test_app/src/Controller/EmployeesController.php
> Refactor OpenApiSearch to better support TableLocator::get

- src/Lib/Configuration.php
- tests/TestCase/Controller/SwaggerControllerTest.php
> Removes loading swagger_bake config automatically

- src/Lib/Operation/OperationDocBlock.php
- tests/TestCase/Lib/Operation/OperationDocBlockTest.php
> Docblock parsing of @link not working

- src/Lib/Model/ModelScanner.php
- tests/test_app/src/Model/Table/AbstractTable.php
to prevent exception on abstract AppTable class
> Check if table class is instantiable

- src/Lib/Extension/CakeSearch/Extension.php
- tests/TestCase/Lib/Extension/CakeSearch/ExtensionTest.php
> Adds default schema type to OpenApiSearch query parameters

- src/Lib/Route/RouteDecorator.php
> Allow mixed type for RouteDecorator::prefix

- src/Lib/Route/RouteScanner.php
- tests/TestCase/Lib/Route/PrefixRouteTest.php
- tests/test_app/src/Controller/Api/V1/DepartmentsController.php
> Backport fix for route prefix bug

- .github/workflows/pull-request.yml
> Add PHP 8.2 to CI matrix

- src/Lib/Model/ModelScanner.php
> Check if class is subclass of Table in ModelScanner

- docs/attributes.md
- src/Lib/Attribute/OpenApiPathParam.php
- tests/TestCase/Lib/Attribute/OpenApiPathParamTest.php
- tests/TestCase/Lib/OpenApi/ParameterTest.php
> Add isRequired property to OpenApiPathParam attribute

- src/Lib/Operation/DtoParser.php
- tests/TestCase/Lib/Operation/OperationQueryParameterTest.php
- tests/TestCase/Lib/Operation/OperationRequestBodyTest.php
- tests/test_app/src/Dto/EmployeeData.php
Ref: #502 
Adds some extra test coverage while debugging an issue. No released needed.
> Adds test coverage for DTOs

- src/Lib/Configuration.php
> Add error handling for when config is missing

- src/Lib/Configuration.php
- src/Lib/Service/OpenApiControllerService.php
> Extendable configuration

- composer.json
- src/Lib/Extension/CakeSearch/Extension.php
- src/Lib/Factory/SwaggerFactory.php
- src/Lib/OpenApiPathGenerator.php
- src/Lib/OpenApiSchemaGenerator.php
- src/Lib/Swagger.php
Just adding some performance tracking to compare between current and future versions.
> Adds timers and memory tracking if DebugKit is loaded

- .github/workflows/pull-request.yml
- src/Lib/Operation/OperationFromRouteFactory.php
- tests/TestCase/Lib/Attribute/OpenApiOperationTest.php
- tests/test_app/src/Controller/OperationsController.php
> Response attribute takes precedence over doc block

- src/Lib/Configuration.php
- tests/TestCase/Lib/ConfigurationTest.php
- tests/TestCase/Lib/Operation/OperationResponseAssociationTest.php
> Only do file exists check for YML config

- src/Lib/Attribute/AbstractSchemaProperty.php
- tests/TestCase/Lib/Attribute/OpenApiSchemaPropertyTest.php
> Fix bug, isNullable is not being set from Attribute

- src/Lib/OpenApi/SchemaProperty.php
- tests/TestCase/Lib/MediaType/GenericTest.php
Fixes bug introduced in https://github.com/cnizzardini/cakephp-swagger-bake/releases/tag/v3.3.0 breaking most collection schemas :-(
> Fixes schema collection bug
