- src/Lib/Operation/ExceptionHandler.php
- src/Lib/Operation/OperationResponse.php
- tests/TestCase/Lib/Operation/ExceptionHandlerTest.php
- Set exception description from doc block
- ExceptionHandler constructor was refactored to accept Throws instance
- Modify unit tests and add new one.
> Support descriptions on @throw tags #44

- README.md
- src/Lib/Annotation/SwagOperation.php
- src/Lib/Operation/OperationFromRouteFactory.php
- tests/TestCase/Lib/Operation/OperationFromRouteFactoryTest.php
- tests/test_app/src/Controller/EmployeesController.php
- Added `@SwagOperation(tagNames=array)` which accepts the annotation
array syntax `{"el 1", "el 2"}`
- Added unit test
- Updated readme
> Override default tag attribute #42

- src/Lib/Path/PathFromRouteFactory.php
When `$fullyQualifiedNamespace` is null, the `isVisible()` method blows up because it is expecting a string as an argument but null get passed to it. This fix prevents null from being passed into the `isVisible()` method.
> Handle null FQN from NamespaceUtility::getControllerFullQualifiedNameSpace()

- src/Controller/Component/SwaggerUiComponent.php
Allows a better check of component is in registry. Since the Flash component is lazily loaded using  
```
public $components = ['Flash'];
```
this `isset($this->Flash)` returns false until the component is first used.
> check if Flash component is loaded in component registry

- assets/swagger.yml
- src/Lib/OpenApi/Schema.php
- src/Lib/OpenApi/Xml.php
- src/Lib/Operation/OperationRequestBody.php
- src/Lib/Operation/OperationResponse.php
- src/Lib/Schema/SchemaFromYamlFactory.php
- src/Lib/Schema/SchemaPropertyFromYamlFactory.php
- src/Lib/Swagger.php
- tests/test_app/config/swagger-with-existing.yml
- Added new OpenApi/Xml class
- Updated assets to include xml->name = response
- Updated unit tests
- Added OpenApi/Schema::xml
- Update OperationRequestBody and OperationResponse to use new Xml class
- Created Yaml Schema and SchemaProperty factories which includes Xml
and other properties that were missed
> XML example cannot be generated; root element name is undefined (#82)

- src/Lib/Decorator/EntityDecorator.php
- src/Lib/Schema/SchemaPropertyFactory.php
- src/Lib/Schema/SchemaPropertyFormat.php
- src/Lib/Schema/SchemaPropertyValidation.php
- src/Lib/Utility/NamespaceUtility.php
- tests/TestCase/Lib/Schema/SchemaPropertyFormatTest.php
- tests/TestCase/Lib/Schema/SchemaPropertyValidationTest.php
- Added SchemaPropertyFormat class
- Call new class from SchemaPropertyFactory
- Added unit tests
- Refactored unit tests for SchemaPropertyValidation to reduce lines
of code and improve speed
- Fixed some items found by phpcs
> Set SchemaProperty::format from Cake Validator rules (#88)

- src/Lib/Decorator/EntityDecorator.php
- src/Lib/Schema/SchemaPropertyValidation.php
- src/Lib/Utility/NamespaceUtility.php
- tests/TestCase/Lib/Schema/SchemaPropertyValidationTest.php
This is actually for #87 
- SchemaPropertyValidator and tests:
- - Translate Validator::lengthBetween to minLength and maxLenth
- - Instructed phpunit coverage to ignore methods which are clearly
covered by multiple tests
- - Some light refactoring
- PHPCS fixes to EntityDecorator and NamespaceUtility
> Adds support for Validator::lengthBetween(), plus phpcs fixes (#89)

- src/Command/BakeCommand.php
- src/Command/CommandTrait.php
- src/Command/InstallCommand.php
- src/Command/ModelCommand.php
- src/Command/RouteCommand.php
- src/Lib/Operation/OperationSecurity.php
- src/Plugin.php
Fixes the warning noted in the bug report and a warning message from OperationSecurity if a securitySchema is not defined in swagger.yml
- Config file is no longer loaded in Plugin->bootstrap() if being run through the CLI
- For CLI the config is now load via CommandTrait->loadConfig()
- `bin/cake swagger install` does not load the config any longer
- Prevent warning in OperationSecurity->assignAuthenticationComponent() with isset() check.
- Made some improvements to order of operations with the installer
> Fixes warning during install and other bugs found during regression #117

- src/Lib/Operation/OperationResponse.php
- src/Lib/Swagger.php
- tests/TestCase/Lib/SwaggerOperationTest.php
See notes in #119
- Combined conditions into a single if for schema and has success code check
- Removed duplicate code fragment for setting Schema on Response->content->schema and mimeType
- Removed duplicate check for whether the action is a CRUD action
- Removes the display of array of objects in OpenAPI schema.
- Logic for showing array of objects on index actions was moved inside Operation->Response->Content->Schema
- Some refactoring and cleanup was also performed in assignSchema()
A bug was found in OperationResponse->assignSchema() related to XML
mime types, setXml(null) is called on each iteration to avoid all mime
types showing XML data.
Improved performance of SwaggerOperationTest by moving not rebuilding
Swagger instance for each test. Methods that need a custom Swagger …
> Do not display Array of Objects in OpenApi Schema #119

- README.md
- src/Lib/Annotation/SwagRequestBodyContent.php
- src/Lib/Operation/OperationFromRouteFactory.php
- src/Lib/Operation/OperationRequestBody.php
- tests/TestCase/Lib/Annotations/SwagRequestBodyContentTest.php
- tests/TestCase/Lib/Operation/OperationRequestBodyTest.php
- tests/test_app/src/Controller/EmployeesController.php
- tests/test_app/src/Controller/SwagRequestBodyContentController.php
Deprecated SwagRequestBodyContent->mimeType in favor of mimeTypes
Accept an array for mimeTypes to reduce the amount of annotations needed
> Deprecated SwagRequestBodyContent->mimeType in favor of mimeTypes

- README.md
- src/Lib/Annotation/SwagResponseSchema.php
- src/Lib/Operation/OperationResponse.php
- tests/TestCase/Lib/Operation/OperationResponseTest.php
Accept an array instead to reduce the amount of annotations. If no mimeTypes
is supplied, default to values in config responseContentTypes.
- Update README
- Update unit tests
> Add SwagResponseSchema->mimeTypes <array> and deprecated mimeType

- docs/extensions.md
- src/Lib/Swagger.php
Moves event trigger into toString and provides setArray. Adds better examples to readme.
> Fixes bug with using SwaggerBake.beforeRender #202

- assets/swagger.yml
- assets/x-swagger-bake.yaml
- docs/extensions.md
- src/Lib/MediaType/Generic.php
- src/Lib/MediaType/GenericTrait.php
- src/Lib/MediaType/Xml.php
- src/Lib/OpenApi/Schema.php
- src/Lib/Operation/OperationFromRouteFactory.php
- src/Lib/Operation/OperationResponse.php
- src/Lib/Swagger.php
- tests/TestCase/Lib/Operation/OperationResponseTest.php
Resolves #205
- Modifies MediaType/Generic and MediaType/XML to read in Generic-Collection for samples if defined.
- Modifies OperationResponse so it can access openapi array from Swagger as a dependency.
- Modifies Swagger to merge user-defined additions to x-swagger-bake vendor space
- Updates unit tests.
Refactors:
- Fixes sample schema for HalJson-Collection
- Moves shared logic between Generic and XML into Generic Trait
- Adds Schema::setVendorProperty for creating adhoc vendor attributes
- Adds SwaggerBake.initialize event
- Updates docs/extensions.md with new functionality
> Adds support for a Generic Collection

- .github/workflows/php.yml
- README.md
- composer.json
- src/Lib/Configuration.php
- src/Lib/Operation/ExceptionHandler.php
- tests/TestCase/Lib/Utility/NamespaceUtilityTest.php
Resolves #227
- Adds PHP 8.0 to builds
- Disables PHPMD until it supports PHP 8.0
- Resolves changes in CakePHP exceptions
> Cake 4.2 and PHP 8.0 support

- assets/swagger_bake.php
- src/Lib/Configuration.php
- src/Lib/Swagger.php
- tests/TestCase/Lib/SwaggerTest.php
Also, to keep the new `jsonOptions` optional and don't break BC, I applied default $config also into directed injected array on `Configuration::__construct`.
> Allow override json_encode options from swagger_bake config

- src/Command/ModelCommand.php
- src/Command/RouteCommand.php
Add support for --config to swagger models and swagger routes... 
`bin/cake swagger models` now sort results alphabetically
> Add --config to routes and models commands enhancement

- docs/annotations.md
- src/Lib/Annotation/SwagResponseSchema.php
- src/Lib/MediaType/AbstractMediaType.php
- src/Lib/MediaType/Generic.php
- src/Lib/MediaType/HalJson.php
- src/Lib/MediaType/JsonLd.php
- src/Lib/MediaType/MediaTypeInterface.php
- src/Lib/MediaType/Xml.php
- src/Lib/OpenApi/Schema.php
- src/Lib/Operation/OperationFromRouteFactory.php
- src/Lib/Operation/OperationRequestBody.php
- src/Lib/Operation/OperationResponse.php
- src/Lib/Operation/OperationResponseException.php
- src/Lib/Swagger.php
- tests/TestCase/Lib/Annotations/SwagResponseSchemaTest.php
- tests/TestCase/Lib/MediaType/GenericTest.php
- tests/TestCase/Lib/MediaType/HalJsonTest.php
- tests/TestCase/Lib/MediaType/JsonLdTest.php
- tests/TestCase/Lib/MediaType/XmlTest.php
- tests/TestCase/Lib/Operation/OperationResponseTest.php
- tests/TestCase/Lib/Operation/OperationResponseYamlTest.php
- tests/test_app/src/Controller/EmployeesController.php
- Removes deprecated properties from SwagResponseSchema
- Remove SwagResponseSchema.schemaItems
- Updates documentation in annotations.md
- Refactors all MediaType classes to use schemaType instead of crud
action
- Breaks parsing `@throw` tag for exception responses into its own class,
was previously part of OperationResponse, now OperationResponseException.
- Removes getters for write, add, edit, read schemaRefs from Schema
class. Use new refPath property instead. This is set when schema is
added now.
- Removes const SCHEMA from Schema class
- Updates unit tests.
> Refactors OperationResponse, SwagResponseSchema, and MediaTypes

- .github/workflows/php.yml
- src/Command/CommandTrait.php
- src/Lib/Operation/ExceptionHandler.php
- src/Lib/Schema/SchemaFactory.php
Resolves #339 
- Adds checks for CakePHP 4.0 - 4.3 when running as PHP 7.4
- Fixes some minor compatibility issues in CakePHP 4.0 and 4.1
> CakePHP compatibility check

- src/Lib/Operation/OperationResponse.php
- tests/TestCase/Lib/Operation/OperationResponseTest.php
Allows support for changing default success schema. For example:
```php
#[OpenApiResponse(statusCode: '201')]
public function add()
```
> Allow changing default success schema

- composer.json
- src/Controller/SwaggerController.php
- src/Lib/Operation/OperationFromRouteFactory.php
- src/Lib/Route/RouteDecorator.php
- src/Lib/Route/RouteScanner.php
- tests/TestCase/Lib/Route/RouteDecoratorTest.php
- tests/TestCase/Lib/Route/RouteScannerTest.php
- tests/test_app/plugins/Demo/src/Controller/TestController.php
- tests/test_app/plugins/Demo/src/Plugin.php
Reference: #399
This PR does two things:
- Sets the base namespace for a controller to either the plugin name or the value of `App.namespace` in the RouteScanner. This resolves the issue reported by @aginev
- Conditionally prefixes the plugin name to the OpenAPI tag (if the controller belongs to a plugin).
> Plugin routes not showing due to namespace collision

- composer.json
- src/Lib/OpenApi/SchemaProperty.php
- src/Lib/Schema/SchemaFactory.php
- src/Lib/Schema/SchemaPropertyFactory.php
- tests/Fixture/EmployeesFixture.php
- tests/TestCase/Lib/SwaggerSchemaTest.php
- tests/test_app/src/Model/Entity/Employee.php
Adds support for [Entity](https://book.cakephp.org/4/en/orm/entities.html) `$_accessible` and `$_hidden` properties and will now properly set OpenAPI writeOnly and readOnly properties.
- readOnly when not accessible and not hidden.
- writeOnly when accessible and is hidden.
- never display properties when is not accessible and is hidden.
> Entity mass assignment support

- README.md
- src/Command/InstallCommand.php
- src/Lib/Configuration.php
- src/Plugin.php
Loading the config in bootstrap breaks the installer and probably shouldn't have done in the first place. This will be a breaking change and users must now manually load the config in their `config/bootstrap.php`.
> breaking change to remove config loading from plugin bootstrap

- docs/attributes.md
- src/Lib/OpenApi/Schema.php
- src/Lib/Schema/SchemaFromYamlFactory.php
- src/Lib/Utility/OpenApiDataType.php
- tests/TestCase/Lib/Schema/SchemaFromYamlFactoryTest.php
- tests/test_app/config/test-cases.yml
Adds support for the following YAML:
```yaml
Year:
type: array
items:
type: integer
example: [2022, 2021, 2020]
```
So it can be referenced like this:
```php
#[OpenApiResponse(schemaType: '', ref: '#/components/schemas/Year')]
```
> Support array list from yaml

- src/Lib/Route/RouteDecorator.php
- tests/TestCase/Lib/Route/RouteDecoratorTest.php
- tests/test_app/src/Controller/Api/V1/DepartmentsController.php
Ref #478 
Fixes setting RouteDecorator::controllerFqn when route prefix contains a forward slash.
> Fix bug with forward slashes in route prefixes

- src/Lib/OpenApi/Schema.php
(I figured out what I was doing wrong, the trait is in the PHP global namespace so you have to prefix it with a backslash.)
This references bug #500 
Three solutions exist that we know of to suppress the error:
1. Turning debug mode off in your Cake app so deprecation errors get swallowed
2. Adding `#[\AllowDynamicProperties]` to `src/Lib/OpenApi/Schema.php`
3. Same class as above, but extending stdClass like this: `class Schema extends \stdClass implements JsonSerializable, SchemaInterface` (again, note backslash)
This PR implements **Solution 2**. I'm also using Solution 1 in production (because I don't run debug mode in prod). I'm unsure of all the ramifications of Solution 3 (extending stdClass sounds like it comes with a lot of baggage) so I didn't go that route.
Important note: …
> Add trait to suppress dynamic properties error

- src/Lib/OpenApi/SchemaProperty.php
- src/Lib/OpenApi/SchemaTrait.php
- src/Lib/Schema/SchemaPropertyFactory.php
- src/Lib/Utility/DataTypeConversion.php
- src/Lib/Utility/OpenApiDataType.php
- tests/Fixture/DepartmentsFixture.php
- tests/TestCase/Lib/Schema/SchemaFactoryTest.php
- tests/TestCase/Lib/Schema/SchemaPropertyFactoryTest.php
- tests/TestCase/Lib/Utility/DataTypeConversionTest.php
- tests/test_app/src/Model/Table/DepartmentEmployeesTable.php
- tests/test_app/src/Model/Table/DepartmentsTable.php
- tests/test_app/src/Model/Table/EmployeeSalariesTable.php
- tests/test_app/src/Model/Table/EmployeeTitlesTable.php
Adds support for CakePHP/MySQL data type of JSON with the following OpenAPI schema:
```yaml
json_field:
oneOf:
- type: object
- type: array
items: []
```
Ref: #507 
Misc: Cleans up some annotations in tests.
> Adds support for json type

- docs/attributes.md
- src/Lib/Attribute/AbstractSchemaProperty.php
- src/Lib/OpenApi/SchemaProperty.php
- tests/TestCase/Lib/Attribute/OpenApiSchemaPropertyTest.php
Resolves: #512 
The attribute now accepts an `items` property for setting array properties, otherwise it defaults to an empty array.
> Fixes OpenApiSchemaProperty(name: 'propert_name', type: 'array') not working

- .github/workflows/pull-request.yml
- composer.json
> Require CakePHP 5 for version 3

- docs/attributes.md
- src/Lib/Operation/OperationResponseAssociation.php
- tests/TestCase/Lib/Operation/OperationResponseAssociationTest.php
- tests/bootstrap.php
> Merge from 2.x

- src/Lib/Schema/SchemaFactory.php
- tests/TestCase/Lib/SwaggerSchemaTest.php
Resolves #546
Hidden properties were correctly not showing in operation response sample, but still displaying in schema sample. This hides them always.
> Hidden properties take precedence in being hidden

- src/Lib/OpenApi/SchemaProperty.php
- tests/TestCase/Lib/OpenApi/SchemaPropertyTest.php
> Pass enums through array_values

- composer.json
- src/Lib/Route/RouteDecorator.php
- tests/TestCase/Lib/Route/RouteDecoratorTest.php
- tests/test_app/plugins/Orgname/Special/src/Controller/MyController.php
- tests/test_app/plugins/Orgname/Special/src/Plugin.php
> Fix plugin with `/` in the name

- src/Lib/OpenApi/SchemaProperty.php
Fixes custom array schema's resulting in output like this in swagger:
```json
{
"array_property": [
"string"
]
}
```
Now supports defining custom array like this:
```php
(new SchemaProperty('foo_schemas', 'array'))->setItems([
[
'type' => 'object',
'allOf' => [['$ref' => '#/components/schemas/FooSchema']]
]
]),
```
outputting...
```json
"foo_schemas": [
{
"id": 0,
"name": "string",
}
],
```
> Fix custom array schema
